# theme: jekyll-theme-slate
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
collections:
  challenges:
    output: false
  weeks:
    output: true
  python:
    output: true
  exercises:
    output: true
  lectures:
    output: true
  slides:
    output: false

defaults:
  - scope:
      path: ""
      type: "weeks"
    values:
      layout: "week"
  - scope:
      path: ""
      type: "lectures"
    values:
      layout: "lecture"
  - scope:
      path: ""
      type: "exercises"
    values:
      layout: "exercise"
  - scope:
      path: ""
      type: "python"
    values:
      lang: "python"
      layout: "reference"
